# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

trigger:
  branches:
    include:
      - main
      - develop
      - release-*
  paths:
    exclude:
      - .github_changelog_generator
      - .gitignore
      - CHANGELOG.md
      - CODE_OF_CONDUCT.md
      - LICENSE.md
      - README.md
      - NuGet.Config
      - assets/*
      - config/*
      - .github/*

# PR always trigger build
pr:
  autoCancel: true

# add nf-tools repo to resources (for Azure Pipelines templates)
resources:
  repositories:
    - repository: templates
      type: github
      name: nanoframework/nf-tools
      endpoint: nanoframework

jobs:

##############################
- job: Build_Library
  condition: >-
    or(
      eq(variables['UPDATE_DEPENDENTS'], 'false'),
      eq(variables['StartReleaseCandidate'], 'true')
    )
  pool:
    vmImage: 'windows-latest'

  variables:
    DOTNET_NOLOGO: true
    solution: 'nanoFramework.Graphics.sln'
    buildPlatform: 'Any CPU'
    buildConfiguration: 'Release'
    nugetPackageName: 'nanoFramework.Graphics'

  steps:

  # step from template @ nf-tools repo
  # all build, update and publish steps
  - template: azure-pipelines-templates/class-lib-build-only.yml@templates
    parameters:
      sonarCloudProject: 'nanoframework_lib-nanoFramework.Graphics'

  # package steps
  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.Graphics'

  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.Graphics.Core'

  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.Graphics.Gc9A01'

  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.Graphics.Ili9341'

  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.Graphics.Ili9342'

  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.Graphics.Otm8009A'

  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.Graphics.Ssd1306'

  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.Graphics.Ssd1331'

  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.Graphics.St7735'

  - template: azure-pipelines-templates/class-lib-package.yml@templates  
    parameters:
      nugetPackageName: 'nanoFramework.Graphics.St7789'

  - template: azure-pipelines-templates/class-lib-publish.yml@templates  

  # create GitHub release build from main branch
  - task: GithubRelease@1
    condition: >-
      and(
        succeeded(),
        eq(variables['System.PullRequest.PullRequestId'], ''),
        startsWith(variables['Build.SourceBranch'], 'refs/heads/main'),
        not(contains(variables['Build.SourceBranch'], 'preview')),
        eq(variables['StartReleaseCandidate'], false)
      )
    displayName: Create/Update GitHub release
    inputs:
      action: edit
      gitHubConnection: 'github.com_nano-$(System.TeamProject)'
      tagSource: userSpecifiedTag
      tag: v$(MY_NUGET_VERSION)
      title: '$(nugetPackageName) Library v$(MY_NUGET_VERSION)'
      releaseNotesSource: inline
      releaseNotesInline: 'Check the [changelog]($(Build.Repository.Uri)/blob/$(Build.SourceBranchName)/CHANGELOG.md).<br><br><h4>Install from NuGet</h4><br>The following NuGet packages are available for download from this release:<br>:package: [.NET](https://www.nuget.org/packages/$(nugetPackageName)/$(MY_NUGET_VERSION)) v$(MY_NUGET_VERSION).<br>:package: [.NET (client API only)](https://www.nuget.org/packages/nanoFramework.System.Net.Http.Client/$(MY_NUGET_VERSION)) v$(MY_NUGET_VERSION)<br>:package: [.NET (server API only)](https://www.nuget.org/packages/nanoFramework.System.Net.Http.Server/$(MY_NUGET_VERSION)) v$(MY_NUGET_VERSION)'
      assets: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      assetUploadMode: replace
      isPreRelease: false
      addChangeLog: false

##################################
# report build failure to Discord
- job: Report_Build_Failure
  
  dependsOn:
  - Build_Library
  condition:  failed('Build_Library')

  pool:
    vmImage: 'windows-latest'

  steps:
  
  - checkout: self

  # step from template @ nf-tools repo
  # report error
  - template: azure-pipelines-templates/discord-webhook-task.yml@templates  
    parameters:
      status: 'failure'
      webhookUrl: '$(DiscordWebhook)'
      message: ''
